USE [master]
GO

/****** Object:  Database [DrinkStore]    Script Date: 14-Apr-17 10:53:49 ******/
CREATE DATABASE [DrinkStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DrinkStore', FILENAME = N'E:\Microsoft SQL Server\MSSQL13.EDGARHUYNH\MSSQL\DATA\DrinkStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DrinkStore_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL13.EDGARHUYNH\MSSQL\DATA\DrinkStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DrinkStore] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DrinkStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DrinkStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DrinkStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DrinkStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DrinkStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DrinkStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [DrinkStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DrinkStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DrinkStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DrinkStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DrinkStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DrinkStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DrinkStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DrinkStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DrinkStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DrinkStore] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DrinkStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DrinkStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DrinkStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DrinkStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DrinkStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DrinkStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DrinkStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DrinkStore] SET RECOVERY FULL 
GO

ALTER DATABASE [DrinkStore] SET  MULTI_USER 
GO

ALTER DATABASE [DrinkStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DrinkStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DrinkStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DrinkStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DrinkStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DrinkStore] SET QUERY_STORE = OFF
GO

USE [DrinkStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DrinkStore] SET  READ_WRITE 
GO

